# Generated by Django 5.0.6 on 2024-05-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_products',
        ),
    ]
