# Generated by Django 5.0.6 on 2024-05-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='palced_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
