# Generated by Django 5.0.6 on 2024-05-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_created_at_alter_order_palced_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_products',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
    ]
