# Generated by Django 5.0.6 on 2024-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_featured_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
