# Generated by Django 5.0.6 on 2024-06-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='palced_at',
            new_name='placed_at',
        ),
    ]
