# Generated by Django 5.0.6 on 2024-06-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_collection_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descrption',
            new_name='description',
        ),
    ]
